### PR TITLE
TCL

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/dbfc492ef87e449a9f816b8f0e9f2424?sid=12ca7741-34ed-4b02-8ad5-a35509124e5b

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/4625578d43ef4e91b3e855cef3878004?sid=9a390659-d59f-488c-bd81-caff589642b7

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/9de90044ebc24a63bda297af0dbee879?sid=eee6287e-de69-4e43-8fac-d68ec389a66e

**Comment by BalajiSriraman** [comment]
the reason why we see the data inserted during the TCL timeline before `COMMIT`

Postgres stores the temp data in buffer pool which is displayed in pgadmin before saving/commiting 

**Postgres under the hood TCL action**

                                           +--------------------+
                                           | Database         |
                                           +--------------------+
                                               |
                                               |
                                               v
                                           +--------------------+
                                           | Buffer Pool       |
                                           +--------------------+
                                               |
                                               |
                                               v
                                           +--------------------+
                                           | Disk Storage      |
                                           +--------------------+

**Comment by BalajiSriraman** [comment]
In the below output, i showed how a simple commit works and how data inserted is stored before committing

explanation quoted^

`https://drive.google.com/file/d/1Ix5AZ4pE74Sc7xN0bEczHf7WKoC5NJvu/view?usp=sharing`
> The reason why we see the data inserted during the TCL timeline before `COMMIT`
> 
> Postgres stores the temp data in buffer pool which is displayed in pgadmin before saving/commiting
> 
> **Postgres under the hood TCL action**
> 
> ```
>                                        +--------------------+
>                                        | Database         |
>                                        +--------------------+
>                                            |
>                                            |
>                                            v
>                                        +--------------------+
>                                        | Buffer Pool       |
>                                        +--------------------+
>                                            |
>                                            |
>                                            v
>                                        +--------------------+
>                                        | Disk Storage      |
>                                        +--------------------+
> ```

**Comment by BalajiSriraman** [comment]
Usage of ROLLBACK

`https://drive.google.com/file/d/1Vxu1MfrB6QOoguNRdwN6hJsy3TwIjGcF/view?usp=sharing`

**Comment by PRASANNAPATHI** [comment]
Hey @BalajiSriraman ,
Explanation & commands are fine.

Please merge it now.

**Pull request merged**
