### PR TITLE
Normalisation

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/463fbf6da0c54a02b2dfad8afb3afd1b?sid=011df7e9-af9c-49a0-ae4c-fdcc0e969c8e

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/87ae5e34e4ca4203a23eb1b5e372af3a?sid=ccdd2162-93b6-42c7-85a9-69171daa10aa

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/801b3571a8604daea45cc68d2ce229dc?sid=9fb35e1c-c74b-4f44-a42c-17f3842604b1

**Comment by BalajiSriraman** [comment]
**RELATIONAL MODEL**

https://www.loom.com/share/7d62114c318f45628492a9b050898744?sid=7a05fd51-3fa2-4bb0-bb41-7ca70d326af8

**Comment by PRASANNAPATHI** [comment]
Yes @BalajiSriraman , your self-viva is sufficient.

Please merge it now.

**Pull request merged**
