### PR TITLE
Milestone-1

### PR DESCRIPTION
**Pull request by BalajiSriraman**
This PR demonstrates the following DBMS concepts 
1. ERD
2. Schema

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/d34fab01c14f495fad6014e3ff17cfc1?sid=939460dc-72a3-4f56-8852-ed725befbc71

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/a386308ef90a4e378b1be6310b927c1d?sid=8041a67f-1ef0-4c15-915b-6b6f0cea28a0

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/9b9f73d9eaf6409fa1bde83902b230a7?sid=b1973abb-5cb3-485b-b2f4-270e7ee72a52

**Comment by PRASANNAPATHI** [comment]
In ERD, Payment should be connected to Ride.
Price should be the foreign key from Ride in Schema.
The Location table is not needed, you can simply have the pickup and dropoff location attributes in the Ride Entity.

**Comment by BalajiSriraman** [comment]
@PRASANNAPATHI 
just wanted to confirm stuff

1. i wanted payment from the **USER** only coz. price have to be calculated in RIDE table (i will be referencing **rideId** as foreign key)

2. Agree that `Price `should be a foreign key (missed it)

3.  i have complicated  Location table so that i would be using **nosql** database in upcoming PRs  🙂

**Comment by PRASANNAPATHI** [comment]
I wanted payment from the USER only coz. price have to be calculated in RIDE table (i will be referencing rideId as foreign key)
>Yes, but ERD is missing with that connection, that's what I mentioned

Agree that Price should be a foreign key (missed it)
>This too collides with the previous statement

I have complicated Location table so that i would be using nosql database in upcoming PRs 🙂
>You should use only sql database for this project

**Comment by BalajiSriraman** [comment]
image


here's the changes 
1. made price to foreign key (rideId can be used to reference from ride table )

**Comment by PRASANNAPATHI** [comment]
Let's have a viva session

Book a slot in my calendar.

**Comment by PRASANNAPATHI** [comment]
Update your design, as discussed

**Comment by BalajiSriraman** [comment]
image

**Comment by BalajiSriraman** [comment]
image


image

**Comment by PRASANNAPATHI** [comment]
Yes Balaji,
It looks fine now.

Please, merge it now.

**Pull request merged**
