### PR TITLE
Role based access control

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/13c912514a964299af73b3c06a391358

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/8b1fc311786740b8a2d32876a6f52b11?sid=31ba5e5e-2d85-4e82-847f-c8bd579f8189

**Comment by BalajiSriraman** [comment]
in the output of executing create role , since i aldready had 3 roles just for viva purposes i made a role named "`User`"

https://drive.google.com/drive/folders/1P_hwlyi0gPL3_419HlLodwpfY3uxQSyA?usp=sharing

**Comment by PRASANNAPATHI** [comment]
Hey @BalajiSriraman ,
Your explanation and execution are fine for this concept.
Everything is sufficient.

Please merge it for RBAC.

**Pull request merged**
