### PR TITLE
DDL

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/eef541fe30ee416ca20903bfc078b3e1?sid=f293bd16-3386-4410-9af7-af5a43ea4770

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/a095101e6cd941ebb49c42fbfe0a7669?sid=b20a8aa9-1863-4880-9aa4-f9ad2cae3fa5

**Comment by BalajiSriraman** [comment]
Here's the video for executing all the sql queries used in the PR

https://drive.google.com/file/d/10CBvvZ73_LqSnYcPOm-qgpG-m7-yGMBu/view?usp=share_link

**Comment by PRASANNAPATHI** [comment]
Hey @BalajiSriraman ,
your explanation is fine, but execution is not meeting the requirements.

Please book a slot using the link shared in wiki for viva.

**Comment by PRASANNAPATHI** [comment]
Hi @BalajiSriraman  

Approved in viva,

Please merge it for DDL

**Pull request merged**
