### PR TITLE
Advanced SQL Queries - Joins, subqueries

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/996b92f13f31433fb3a9a56af5026f9e?sid=c1e4f1d7-3095-4992-8fd5-d5d6e6b1713f

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/7003f64a9f104b8ca7fd1f1da580d5d0?sid=40f88616-2281-44d8-9926-08904d7ab5ec

**Comment by BalajiSriraman** [comment]
Output:
https://drive.google.com/file/d/1ivjLaGx-D2UPfYDpP98vcL8pREhrCL6u/view?usp=sharing

**Comment by PRASANNAPATHI** [comment]
Hey @BalajiSriraman ,

Your explanation is good.

But only 2 commands is not sufficient, we need atleast 3 queries, Also I can see subquery is missing. 
And the functionality of the queries is little confusing.

Can you please Book a slot for viva, Be ready with atleast 3 queries along with subquery as mentioned.

**Comment by PRASANNAPATHI** [comment]
Approved in viva.

Please merge it now.

**Pull request merged**
