### PR TITLE
Indexing And Query Optimization

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/7b9fbeccb5184914b582020fde011e3b?sid=8994ad94-d8e2-4881-ab3b-be28422f27b6

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/7d4df718e7f34f4886b959950806d083?sid=774449bb-7b23-44de-9082-aec19854f0bf

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/b70f68a52037411ea43bdf1b13008506?sid=9a865fb6-bc41-4a09-b292-ec6ddace5c4f

**Comment by BalajiSriraman** [comment]
Querying before indexing

#https://user-images.githubusercontent.com/96479581/277154558-b8ec3030-606b-44ad-8709-da55a8c23c8c.png

**Comment by BalajiSriraman** [comment]
indexing
#https://user-images.githubusercontent.com/96479581/277154598-0c3ee5b3-30fc-4711-93b8-fc347b3f7698.png

**Comment by BalajiSriraman** [comment]
Fast Querying after indexing

#https://user-images.githubusercontent.com/96479581/277154622-f17eb17b-947d-4ec9-8fbd-b3971e3ad386.png

**Comment by PRASANNAPATHI** [comment]
Hey @BalajiSriraman ,

Your self explanation and commands are fine and sufficient for this concept.

Please merge it.

**Pull request merged**
