### PR TITLE
DML

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/1850489ca4144eb89e563e48a89c3b55?sid=d707a8fa-acb4-432b-892f-9721cffd3ce3

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/52f439864b764611bbcff570ff459a0a?sid=dd6e7548-35e3-4a7e-8d3f-407f569f61c6

**Comment by BalajiSriraman** [comment]
output:
https://drive.google.com/drive/folders/1pVXrZycsnVJ3SGfmE9fbEKQhEhvV_SWN?usp=sharing

**Comment by PRASANNAPATHI** [comment]
Hey @BalajiSriraman , Your explanation was good and sufficient,

But about execution, it is not sufficient, you need to speak and explain what is happening.
For all commands - you need to show the change in tables.(Not just query executed message)

You can merge it for DML.

If you wish to score fully, please submit the execution video with proper requirements as mentioned above.

**Comment by PRASANNAPATHI** [comment]
Approved in Viva,

Please merge it now.

**Pull request merged**
